services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: db123
      MYSQL_DATABASE: db_takeHome
      # MYSQL_USER: root
      MYSQL_PASSWORD: db123
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_HOST: db
      DB_DATABASE: db_takeHome
      DB_USERNAME: root
      DB_PASSWORD: db123
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  dbdata:
